
/**
 * OOPSBannerApp UC2 – Banner Display Application
 *
 * This class demonstrates the creation of a visual banner displaying the word "OOPS"
 * using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
 * console using individual print statements for each line, creating a decorative
 * text effect.
 *
 * <p>The banner is generated by printing predefined string patterns line by line,
 * where each line contributes to forming the letters O, O, P, and S in a stylized format.
 * This extends a basic user story by adding visual presentation to a simple message output.
 * </p>
 *
 * @author Tulsi
 * @version 6
 */

public class OOPSBannerApp {

    public static void main(String[] args) {

        // Get patterns using helper methods
        String[] O = getOPattern();
        String[] P = getPPattern();
        String[] S = getSPattern();

        // Assemble banner using method-returned arrays
        String[] banner = new String[7];

        for (int i = 0; i < 7; i++) {
            banner[i] = String.join("  ", O[i], O[i], P[i], S[i]);
        }

        // Print using enhanced for loop
        for (String line : banner) {
            System.out.println(line);
        }
    }

    // Helper method for O
    public static String[] getOPattern() {
        return new String[]{
                "  *****  ",
                " *     * ",
                " *     * ",
                " *     * ",
                " *     * ",
                " *     * ",
                "  *****  "
        };
    }

    // Helper method for P
    public static String[] getPPattern() {
        return new String[]{
                "*******  ",
                "*     *  ",
                "*     *  ",
                "*******  ",
                "*        ",
                "*        ",
                "*        "
        };
    }

    // Helper method for S
    public static String[] getSPattern() {
        return new String[]{
                "  *****  ",
                " *       ",
                " *       ",
                "  *****  ",
                "       * ",
                "       * ",
                "  *****  "
        };
    }
}