
/**
 * OOPSBannerApp UC2 – Banner Display Application
 *
 * This class demonstrates the creation of a visual banner displaying the word "OOPS"
 * using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
 * console using individual print statements for each line, creating a decorative
 * text effect.
 *
 * <p>The banner is generated by printing predefined string patterns line by line,
 * where each line contributes to forming the letters O, O, P, and S in a stylized format.
 * This extends a basic user story by adding visual presentation to a simple message output.
 * </p>
 *
 * @author Tulsi
 * @version 5
 */
// Extend the user story 4 to further develop the OOPS Banner Application by
// not only using String arrays to hold banner lines and printing them in a
// loop. But also by defining and populating the array in a more concise way
// at the time of declaration using String.join() method to create each line
// of the banner.

public class OOPSBannerApp {

    public static void main(String[] args) {

        // UC5: inline array initialization using String.join() for each banner line
        String[] banner = new String[] {
            String.join("  ",
                "  *****  ",   // O row 0
                "  *****  ",   // O row 0 (second O)
                "*******  ",   // P row 0
                "  *****  "    // S row 0
            ),
            String.join("  ",
                " *     * ",   // O row 1
                " *     * ",
                "*     *  ",   // P row 1
                " *       "    // S row 1
            ),
            String.join("  ",
                " *     * ",
                " *     * ",
                "*     *  ",
                " *       "
            ),
            String.join("  ",
                " *     * ",
                " *     * ",
                "*******  ",
                "  *****  "
            ),
            String.join("  ",
                " *     * ",
                " *     * ",
                "*        ",
                "       * "
            ),
            String.join("  ",
                " *     * ",
                " *     * ",
                "*        ",
                "       * "
            ),
            String.join("  ",
                "  *****  ",
                "  *****  ",
                "*        ",
                "  *****  "
            )
        };

        // print using enhanced for-loop (requirement)
        for (String line : banner) {
            System.out.println(line);
        }
    }
}