
/**
 * OOPSBannerApp UC2 – Banner Display Application
 *
 * This class demonstrates the creation of a visual banner displaying the word "OOPS"
 * using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
 * console using individual print statements for each line, creating a decorative
 * text effect.
 *
 * <p>The banner is generated by printing predefined string patterns line by line,
 * where each line contributes to forming the letters O, O, P, and S in a stylized format.
 * This extends a basic user story by adding visual presentation to a simple message output.
 * </p>
 *
 * @author Tulsi
 * @version 3
 */
// Extend use case UC2 to use String.join() method to create each line of the "OOPS" banner
// instead of concatenating strings with the + operator. This is essentially to overcome the
// drawbacks of using the + operator for string concatenation which essentially creates
// multiple intermediate String objects in memory leading to inefficiency.


public class OOPSBannerApp {
    // Main method to run the banner display
    // Use System.out.println() to print each line of the OOPS banner to create
    // the visual effect for the message "OOPS". Construct each line using
    // String.join() method for better readability and efficiency.
    // Each line corresponds to a row in the banner for the letters O, O, P, S.
    public static void main(String[] args) {

        // Line 1
        System.out.println(
                String.join(" ",
                        "  *****  ",
                        "  *****  ",
                        " ******  ",
                        "  *****  ")
        );

        // Line 2
        System.out.println(
                String.join(" ",
                        " *     * ",
                        " *     * ",
                        " *     * ",
                        " *       ")
        );

        // Line 3
        System.out.println(
                String.join(" ",
                        "*       *",
                        "*       *",
                        "*       *",
                        "*       ")
        );

        // Line 4
        System.out.println(
                String.join(" ",
                        "*       *",
                        "*       *",
                        " ******  ",
                        " ******  ")
        );

        // Line 5
        System.out.println(
                String.join(" ",
                        "*       *",
                        "*       *",
                        " *       ",
                        "       * ")
        );

        // Line 6
        System.out.println(
                String.join(" ",
                        " *     * ",
                        " *     * ",
                        " *       ",
                        " *     * ")
        );

        // Line 7
        System.out.println(
                String.join(" ",
                        "  *****  ",
                        "  *****  ",
                        " *       ",
                        "  *****  ")
        );
    }
}

